plugins {
    id 'org.asciidoctor.jvm.convert' version '3.3.2'
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.9'
    id 'com.google.protobuf' version '0.9.4'
}

dependencies {
    implementation "io.grpc:grpc-netty-shaded:${grpcVersion}"
    implementation "io.grpc:grpc-protobuf:${grpcVersion}"
    implementation "io.grpc:grpc-stub:${grpcVersion}"
    implementation "com.google.protobuf:protobuf-java:${protobufVersion}"
    compileOnly 'org.apache.tomcat:annotations-api:6.0.53'
}

test {
    useJUnitPlatform()
    jvmArgs '--add-opens=java.base/java.lang=ALL-UNNAMED'
}

asciidoctor{

    resources {
        from('src/docs/asciidoc/images') {
            include '**/*.png'
        }

        into './images'
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${protobufVersion}"
    }
    plugins {
        grpc {
            artifact = "io.grpc:protoc-gen-grpc-java:${grpcVersion}"
        }
    }
    generateProtoTasks {
        all().each { task ->
            task.plugins {
                grpc {}
            }
        }
    }
}

afterEvaluate { tasks.findByName("clean").doLast {
    delete protobuf.generatedFilesBaseDir
}}


sourceSets {
    main {
        proto {
            srcDir 'src/main/protobuf'
            include '**/*.proto'
        }
    }
}


nextflowPlugin {
    nextflowVersion = "${nextflowVersion}"

    description = 'A plugin to use IBM aspera protocol in pipelines'
    provider = " Incremental Steps"
    className = 'incsteps.plugin.NfAsperaPlugin'
    extensionPoints = [
        'incsteps.plugin.NfAsperaExtension',
    ]


}
